#!/bin/bash

# A script to display a series of numbers using a while loop.

i=1
while [[ "$i" -le 10 ]]; do
    echo "the count is at - $i"
    i=$((i + 1))
done 

echo "the count is done until $((i-1))"