#!/bin/bash

# A script that will ask for a number and print out a message depending on the value. 

read -p "Enter a value: " n
case $n in
    1|2) 
        echo "One or two";;
    [3-9]) 
        echo "number from 3 to 9";;
    ??) 
        echo "tho charactors";;
    4) 
        echo "Four";;
    *.txt) 
        echo "ends in .txt";;
    *)
        echo "OTHER";;
esac
    