#!/bin/bash

check_even () {
   local mod=2
   echo "The value of mod is $mod"
   if [ $(( $1 % $mod )) -eq 0 ]
   then
      echo "the number $1 is even"
   else
      echo "the number $1 is odd"
   fi 
} 

number=12 
check_even $number
